server {
	listen 8080;
	host 127.0.0.1;
	client_max_body_size 10M;
	root /tmp/webserv-test/www;

	location / {
		allowed_methods GET;
		index index.html;
		autoindex on;
	}

	location /upload/ {
		root /tmp/webserv-test/uploads;
		upload_store /tmp/webserv-test/uploads;
		allowed_methods GET POST DELETE;
		autoindex on;
	}

	location /cgi/ {
		root /tmp/webserv-test/cgi;
		allowed_methods GET POST;

		cgi {
			.py = /usr/bin/python3;
		}
	}
}
