server {
	listen 8080;
	host 0.0.0.0;
	client_max_body_size 10M;
	root www;

	error_page 404 error-pages/404.html;
	error_page 403 error-pages/403.html;
	error_page 500 error-pages/500.html;

	location / {
		allowed_methods GET;
		index login.html;
	}

	location /cgi-bin/ {
		root www/cgi-bin;
		allowed_methods GET POST;

		cgi {
			.py = /usr/bin/python3;
			.php = /usr/bin/php-cgi;
		}
	}

	location /upload/ {
		root uploads;
		upload_store uploads;
		allowed_methods GET POST DELETE;
		autoindex on;
	}
}

server {
	listen 8001;
	host 0.0.0.0;
	client_max_body_size 10M;
	root www;

	error_page 404 error-pages/404.html;
	error_page 403 error-pages/403.html;
	error_page 500 error-pages/500.html;

	location / {
		allowed_methods GET;
		index login.html;
	}

	location /cgi-bin/ {
		root www/cgi-bin;
		allowed_methods GET POST;

		cgi {
			.py = /usr/bin/python3;
			.php = /usr/bin/php-cgi;
		}
	}

	location /game/ {
		root game/america;
		allowed_methods GET POST;

		cgi {
			.penguin = ../../build/penguin_cgi;
		}
	}

	location /upload/ {
		root uploads;
		upload_store uploads;
		allowed_methods GET POST DELETE;
		autoindex on;
	}
}

server {
	listen 8002;
	host 0.0.0.0;
	client_max_body_size 10M;
	root www;

	error_page 404 error-pages/404.html;
	error_page 403 error-pages/403.html;
	error_page 500 error-pages/500.html;

	location / {
		allowed_methods GET;
		index login.html;
	}

	location /cgi-bin/ {
		root www/cgi-bin;
		allowed_methods GET POST;

		cgi {
			.py = /usr/bin/python3;
			.php = /usr/bin/php-cgi;
		}
	}

	location /game/ {
		root game/africa;
		allowed_methods GET POST;

		cgi {
			.penguin = ../../build/penguin_cgi;
		}
	}

	location /upload/ {
		root uploads;
		upload_store uploads;
		allowed_methods GET POST DELETE;
		autoindex on;
	}
}

server {
	listen 8003;
	host 0.0.0.0;
	client_max_body_size 10M;
	root www;

	error_page 404 error-pages/404.html;
	error_page 403 error-pages/403.html;
	error_page 500 error-pages/500.html;

	location / {
		allowed_methods GET;
		index login.html;
	}

	location /cgi-bin/ {
		root www/cgi-bin;
		allowed_methods GET POST;

		cgi {
			.py = /usr/bin/python3;
			.php = /usr/bin/php-cgi;
		}
	}

	location /game/ {
		root game/europe;
		allowed_methods GET POST;

		cgi {
			.penguin = ../../build/penguin_cgi;
		}
	}

	location /upload/ {
		root uploads;
		upload_store uploads;
		allowed_methods GET POST DELETE;
		autoindex on;
	}
}

server {
	listen 8004;
	host 0.0.0.0;
	client_max_body_size 10M;
	root www;

	error_page 404 error-pages/404.html;
	error_page 403 error-pages/403.html;
	error_page 500 error-pages/500.html;
	error_page 503 error-pages/503.html;

	location / {
		allowed_methods GET;
		index login.html;
	}

	location /cgi-bin/ {
		root www/cgi-bin;
		allowed_methods GET POST;

		cgi {
			.py = /usr/bin/python3;
			.php = /usr/bin/php-cgi;
		}
	}

	location /game/ {
		root game/oceania;
		allowed_methods GET POST;

		cgi {
			.penguin = ../../build/penguin_cgi;
		}
	}

	location /upload/ {
		root uploads;
		upload_store uploads;
		allowed_methods GET POST DELETE;
		autoindex on;
	}
}
