#pragma once

#define HTTP_BUFFERSIZE 16384

#define MAX_VIRTUAL_SERVERS (64)
#define MAX_LOCATION_BLOCK_SIZE (16ul * 1024ul)
#define MAX_FILE_SIZE (MAX_LOCATION_BLOCK_SIZE * MAX_VIRTUAL_SERVERS)
#define ARENA_SIZE (2ul * MAX_FILE_SIZE + 4096ul * HTTP_BUFFERSIZE)

#ifdef PIPE_BUF
	#if PIPE_BUF > 4096
		#define ATOMIC_IOSIZE 4096
	#else
		#define ATOMIC_IOSIZE PIPE_BUF
	#endif
#else
	#ifdef _POSIX_PIPE_BUF
		#define ATOMIC_IOSIZE _POSIX_PIPE_BUF
	#else
		#define ATOMIC_IOSIZE 512
	#endif
#endif