#pragma once

#define HTTP_BUFFERSIZE 8192
#define MAX_VIRTUAL_SERVERS (64)

#define MAX_LOCATION_BLOCK_SIZE (16ul * 1024ul)
#define MAX_FILE_SIZE (MAX_LOCATION_BLOCK_SIZE * MAX_VIRTUAL_SERVERS)
#define MAX_PATH_SIZE (4096ul)

#define CONNECTION_POOL_SIZE (4096ul * HTTP_BUFFERSIZE)
#define ARENA_SIZE (2ul * MAX_FILE_SIZE)

#ifdef PIPE_BUF
	#if PIPE_BUF > 4096
		#define ATOMIC_IOSIZE 4096
	#else
		#define ATOMIC_IOSIZE PIPE_BUF
	#endif
#else
	#ifdef _POSIX_PIPE_BUF
		#define ATOMIC_IOSIZE _POSIX_PIPE_BUF
	#else
		#define ATOMIC_IOSIZE 512
	#endif
#endif
